//***  UART Receiver IP ***//
//*** Register Map Generated by Corsair***//
module uart_ip_rx #(
    parameter ADDR_W = 32,
    parameter DATA_W = 32,
    parameter STRB_W = DATA_W / 8
)(

    // System
    input clk,
    input rst,

    // Local Bus
    input  [ADDR_W-1:0] waddr,
    input  [DATA_W-1:0] wdata,
    input               wen,
    input  [STRB_W-1:0] wstrb,
    output              wready,
    input  [ADDR_W-1:0] raddr,
    input               ren,
    output [DATA_W-1:0] rdata,
    output              rvalid,

    // uart rx

    input  i_uart_rx


);

    reg o_ready_reg;

    

    wire [7:0] csr_u_data_data_in;
    wire       o_ready;
    wire       csr_u_ctrl_start_out;


    regs_uart_rx  rx_regs_interface_u1(

        .clk(clk),
        .rst(rst),
        .csr_u_data_data_in(csr_u_data_data_in),
        .csr_u_stat_ready_in(o_ready),
        .csr_u_stat_rx_done_in( !o_ready_reg & o_ready  ),
        .csr_u_ctrl_start_out(csr_u_ctrl_start_out),
        .waddr(waddr),
        .wdata(wdata),
        .wen(wen),
        .wstrb(wstrb),
        .wready(wready),
        .raddr(raddr),
        .ren(ren),
        .rdata(rdata),
        .rvalid(rvalid)

    );


    uart_rx uart_receiver_u1 (

        .clk(clk),
        .rst_n(!rst),
        .rx_data(csr_u_data_data_in),
        .rx_data_ready(csr_u_ctrl_start_out),
        .rx_data_valid(o_ready),
        .rx_pin(i_uart_rx)

    );


    always @(posedge clk) begin
        o_ready_reg <= o_ready;
    end



endmodule