-d C:\Gowin\projects\KRV32_new_counter\impl\gwsynthesis\KRV32_new_counter.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Gowin\projects\KRV32_new_counter\src\rv32.cst
-cfg C:\Gowin\projects\KRV32_new_counter\impl\pnr\device.cfg
-sdc C:\Gowin\projects\KRV32_new_counter\src\picotiny.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 27.000
